"""add_email_sent_to_invitations

Revision ID: 0ea276bf29bc
Revises: 038a7194dd07
Create Date: 2026-01-10 18:58:33.816670

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ea276bf29bc'
down_revision: str | Sequence[str] | None = '038a7194dd07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=False, server_default=sa.text('0'), comment='Whether the invitation email has been sent'))
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True, comment='Timestamp when the email was sent'))
        batch_op.create_index(batch_op.f('ix_invitations_email_sent'), ['email_sent'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_email_sent'))
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('email_sent')

    # ### end Alembic commands ###
