"""drop_permissions_table

Revision ID: 3f032f63cb42
Revises: 084e50e30ae8
Create Date: 2026-01-19 01:35:42.605323

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3f032f63cb42'
down_revision: str | Sequence[str] | None = '084e50e30ae8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_collection'))
        batch_op.drop_index(batch_op.f('ix_permissions_role_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('collection_rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_collection_rules_collection_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_collection_rules_collection_id'))
        batch_op.create_index(batch_op.f('ix_collection_rules_collection_id'), ['collection_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_rules_collection_id'))
        batch_op.create_index(batch_op.f('ix_collection_rules_collection_id'), ['collection_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_collection_rules_collection_id'), ['collection_id'])

    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('collection', sa.VARCHAR(length=255), nullable=False),
    sa.Column('rules', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_collection'), ['collection'], unique=False)

    # ### end Alembic commands ###
