"""create_api_keys_table

Revision ID: 7bccaa56da18
Revises: 147572043440
Create Date: 2026-01-17 14:18:25.159243

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7bccaa56da18'
down_revision: str | Sequence[str] | None = '147572043440'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False, comment='API key ID (UUID)'),
    sa.Column('key_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the API key'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable name for the API key'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Foreign key to users table'),
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Foreign key to accounts table'),
    sa.Column('scopes', sqlite.JSON(), nullable=True, comment='JSON list of permission scopes'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Optional expiration timestamp'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='Whether the API key is active (soft delete)'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful usage'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('ix_api_keys_account_id', ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index('ix_api_keys_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_api_keys_user_id')
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_api_keys_expires_at'))
        batch_op.drop_index('ix_api_keys_account_id')

    op.drop_table('api_keys')
    # ### end Alembic commands ###
