"""create_token_blacklist_table

Revision ID: 92bdd6b3a3bf
Revises: 1a81ce6dcb21
Create Date: 2026-02-14 17:45:30.871856

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '92bdd6b3a3bf'
down_revision: str | Sequence[str] | None = '1a81ce6dcb21'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.alter_column('revoked_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.alter_column('revoked_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
