"""initial_migration

Revision ID: aeef347267b5
Revises: 
Create Date: 2025-12-31 14:24:30.320018

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'aeef347267b5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Account ID (UUID)'),
    sa.Column('account_code', sa.String(length=6), nullable=False, comment='Human-readable account code in XX#### format (e.g., AB1234)'),
    sa.Column('slug', sa.String(length=32), nullable=False, comment='URL-friendly identifier (3-32 chars)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name for the account'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("account_code GLOB '[A-Z][A-Z][0-9][0-9][0-9][0-9]'", name='ck_accounts_code_format'),
    sa.CheckConstraint('length(slug) >= 3 AND length(slug) <= 32', name='ck_accounts_slug_length'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_code'), ['account_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_slug'), ['slug'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier'),
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Account context (UUID)'),
    sa.Column('operation', sa.String(length=10), nullable=False, comment='Operation type: CREATE, UPDATE, DELETE'),
    sa.Column('table_name', sa.String(length=255), nullable=False, comment='Table/collection name'),
    sa.Column('record_id', sa.String(length=36), nullable=False, comment='ID of the affected record'),
    sa.Column('column_name', sa.String(length=255), nullable=False, comment='Name of the changed column'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='Previous value (NULL for CREATE)'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='New value (NULL for DELETE)'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='ID of user who made the change'),
    sa.Column('user_email', sa.String(length=255), nullable=False, comment='Email of user who made the change'),
    sa.Column('user_name', sa.String(length=255), nullable=False, comment='Name of user who made the change'),
    sa.Column('es_username', sa.String(length=255), nullable=True, comment='Electronic signature username'),
    sa.Column('es_reason', sa.Text(), nullable=True, comment='Electronic signature reason'),
    sa.Column('es_timestamp', sa.DateTime(), nullable=True, comment='Electronic signature timestamp'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User agent string from request'),
    sa.Column('request_id', sa.String(length=36), nullable=True, comment='Correlation ID for the request'),
    sa.Column('occurred_at', sa.DateTime(), nullable=False, comment='Timestamp when the change occurred (UTC)'),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='SHA-256 hash of this audit entry'),
    sa.Column('previous_hash', sa.String(length=64), nullable=True, comment='Checksum of the previous audit entry (blockchain chain)'),
    sa.Column('extra_metadata', sqlite.JSON(), nullable=True, comment='Additional metadata as JSON'),
    sa.CheckConstraint("operation IN ('CREATE', 'UPDATE', 'DELETE')", name='ck_audit_log_operation'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_audit_log_account_table', ['account_id', 'table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_audit_log_occurred_at_desc', [sa.literal_column('occurred_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)
        batch_op.create_index('ix_audit_log_table_record', ['table_name', 'record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Collection ID (UUID)'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Collection name (3-64 chars, alphanumeric + underscores)'),
    sa.Column('schema', sa.Text(), nullable=False, comment='JSON schema defining fields, types, and constraints'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_name'), ['name'], unique=True)

    op.create_table('macros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Unique macro name (used as @name in rules)'),
    sa.Column('description', sa.Text(), nullable=True, comment="Description of the macro's purpose"),
    sa.Column('sql_query', sa.Text(), nullable=False, comment='The SQL SELECT query'),
    sa.Column('parameters', sa.Text(), nullable=False, comment='JSON array of parameter names'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='User ID of the creator'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_macros_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment="Role name (e.g., 'admin', 'user')"),
    sa.Column('description', sa.String(length=255), nullable=True, comment="Description of the role's purpose"),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Group ID (UUID)'),
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Foreign key to accounts table'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Group name'),
    sa.Column('description', sa.String(length=500), nullable=True, comment="Description of the group's purpose"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_groups_account_name')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_groups_account_name', ['account_id', 'name'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Foreign key to roles table'),
    sa.Column('collection', sa.String(length=255), nullable=False, comment='Collection name (* for all collections)'),
    sa.Column('rules', sa.Text(), nullable=False, comment='JSON with CRUD rules: {create, read, update, delete}'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_collection'), ['collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='User ID (UUID)'),
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Foreign key to accounts table'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password (bcrypt/argon2)'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Foreign key to roles table'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user can log in'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Timestamp of last successful login'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'email', name='uq_users_account_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_account_email', ['account_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Invitation ID (UUID)'),
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Foreign key to accounts table'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address of the invited user'),
    sa.Column('token', sa.String(length=64), nullable=False, comment='Secure random token for accepting invitation'),
    sa.Column('invited_by', sa.String(length=36), nullable=False, comment='Foreign key to users table (inviter)'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Timestamp when the invitation expires'),
    sa.Column('accepted_at', sa.DateTime(), nullable=True, comment='Timestamp when the invitation was accepted'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index('ix_invitations_account_email', ['account_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index('ix_refresh_tokens_user_account', ['user_id', 'account_id'], unique=False)

    op.create_table('users_groups',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Foreign key to users table'),
    sa.Column('group_id', sa.String(length=36), nullable=False, comment='Foreign key to groups table'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_tokens_user_account')
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))
        batch_op.drop_index(batch_op.f('ix_invitations_account_id'))
        batch_op.drop_index('ix_invitations_account_email')

    op.drop_table('invitations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_account_id'))
        batch_op.drop_index('ix_users_account_email')

    op.drop_table('users')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_collection'))

    op.drop_table('permissions')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('ix_groups_account_name')
        batch_op.drop_index(batch_op.f('ix_groups_account_id'))

    op.drop_table('groups')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('macros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_macros_name'))

    op.drop_table('macros')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_name'))

    op.drop_table('collections')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index('ix_audit_log_table_record')
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_record_id'))
        batch_op.drop_index('ix_audit_log_occurred_at_desc')
        batch_op.drop_index(batch_op.f('ix_audit_log_occurred_at'))
        batch_op.drop_index('ix_audit_log_account_table')
        batch_op.drop_index(batch_op.f('ix_audit_log_account_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_slug'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_code'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
