"""create_password_reset_tokens_table

Revision ID: bb38e4d658cd
Revises: 85e1c8c401fe
Create Date: 2026-01-10 17:05:00.316353

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb38e4d658cd'
down_revision: str | Sequence[str] | None = '85e1c8c401fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Token ID (UUID)'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Foreign key to users table'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address for reset'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the reset token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the token expires'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the token was used'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the token was created'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_password_reset_user_email')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
