"""add_email_verification_tokens_and_user_fields

Revision ID: def3fc1039eb
Revises: b8e206c85cf5
Create Date: 2026-01-10 02:00:31.239894

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'def3fc1039eb'
down_revision: str | Sequence[str] | None = 'b8e206c85cf5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Token ID (UUID)'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Foreign key to users table'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address to be verified'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the verification token'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the token expires'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the token was used'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the token was created'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_email_verification_user_email')
    )
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_verification_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_account_id'))
        batch_op.drop_index(batch_op.f('ix_email_logs_template_type'))

    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_account_id'))
        batch_op.drop_index(batch_op.f('ix_email_templates_enabled'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default='0', nullable=False, comment="Whether the user's email is verified"))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True, comment='Timestamp when the email was verified'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_templates_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_template_type'), ['template_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_verification_tokens_expires_at'))

    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
