"""add migration_revision to collections

Revision ID: ea6f4f210d59
Revises: aeef347267b5
Create Date: 2025-12-31 15:26:26.914718

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea6f4f210d59'
down_revision: str | Sequence[str] | None = 'aeef347267b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migration_revision', sa.String(length=32), nullable=True, comment='Alembic migration revision ID that created/last modified this collection'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('migration_revision')

    # ### end Alembic commands ###
