"""API Schemas for request/response validation."""

from snackbase.infrastructure.api.schemas.auth_schemas import (
    AccountResponse,
    AuthResponse,
    ConflictErrorResponse,
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenRefreshResponse,
    UserResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
)
from snackbase.infrastructure.api.schemas.collection_schemas import (
    CollectionListItem,
    CollectionListResponse,
    CollectionResponse,
    CreateCollectionRequest,
    FieldDefinition,
    GetCollectionsParams,
    SchemaFieldResponse,
    UpdateCollectionRequest,
)
from snackbase.infrastructure.api.schemas.invitation_schemas import (
    InvitationAcceptRequest,
    InvitationCreateRequest,
    InvitationListResponse,
    InvitationResponse,
    InvitationStatus,
)
from snackbase.infrastructure.api.schemas.permission_schemas import (
    CreatePermissionRequest,
    OperationRuleSchema,
    PermissionListResponse,
    PermissionResponse,
    PermissionRulesSchema,
)
from snackbase.infrastructure.api.schemas.record_schemas import (
    RecordListResponse,
    RecordResponse,
    RecordValidationErrorDetail,
    RecordValidationErrorResponse,
)
from snackbase.infrastructure.api.schemas.dashboard_schemas import (
    AuditLogEntry,
    DashboardStats,
    RecentRegistration,
    SystemHealthStats,
)
from snackbase.infrastructure.api.schemas.account_schemas import (
    AccountDetailResponse,
    AccountListItem,
    AccountListResponse,
    AccountUserResponse,
    AccountUsersResponse,
    CreateAccountRequest,
    UpdateAccountRequest,
)

__all__ = [
    "AccountDetailResponse",
    "AccountListItem",
    "AccountListResponse",
    "AccountResponse",
    "AccountUserResponse",
    "AccountUsersResponse",
    "AuditLogEntry",
    "AuthResponse",
    "CollectionListItem",
    "CollectionListResponse",
    "CollectionResponse",
    "ConflictErrorResponse",
    "CreateAccountRequest",
    "CreateCollectionRequest",
    "CreatePermissionRequest",
    "DashboardStats",
    "FieldDefinition",
    "GetCollectionsParams",
    "InvitationAcceptRequest",
    "InvitationCreateRequest",
    "InvitationListResponse",
    "InvitationResponse",
    "InvitationStatus",
    "LoginRequest",
    "OperationRuleSchema",
    "PermissionListResponse",
    "PermissionResponse",
    "PermissionRulesSchema",
    "RecentRegistration",
    "RecordListResponse",
    "RecordResponse",
    "RecordValidationErrorDetail",
    "RecordValidationErrorResponse",
    "RefreshRequest",
    "RegisterRequest",
    "SchemaFieldResponse",
    "SystemHealthStats",
    "TokenRefreshResponse",
    "UpdateAccountRequest",
    "UpdateCollectionRequest",
    "UserResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
]
