"""API Schemas for request/response validation."""

from snackbase.infrastructure.api.schemas.auth_schemas import (
    AccountResponse,
    AuthResponse,
    ConflictErrorResponse,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    RegistrationResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
    SendVerificationRequest,
    TokenRefreshResponse,
    UserResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
    VerifyEmailRequest,
    VerifyResetTokenResponse,
)
from snackbase.infrastructure.api.schemas.collection_schemas import (
    CollectionListItem,
    CollectionListResponse,
    CollectionResponse,
    CreateCollectionRequest,
    FieldDefinition,
    GetCollectionsParams,
    SchemaFieldResponse,
    UpdateCollectionRequest,
)
from snackbase.infrastructure.api.schemas.invitation_schemas import (
    InvitationAcceptRequest,
    InvitationCreateRequest,
    InvitationListResponse,
    InvitationPublicResponse,
    InvitationResponse,
    InvitationStatus,
)
from snackbase.infrastructure.api.schemas.record_schemas import (
    RecordListResponse,
    RecordResponse,
    RecordValidationErrorDetail,
    RecordValidationErrorResponse,
)
from snackbase.infrastructure.api.schemas.dashboard_schemas import (
    DashboardStats,
    RecentRegistration,
    SystemHealthStats,
)
from snackbase.infrastructure.api.schemas.audit_log_schemas import AuditLogResponse
from snackbase.infrastructure.api.schemas.account_schemas import (
    AccountDetailResponse,
    AccountListItem,
    AccountListResponse,
    AccountUserResponse,
    AccountUsersResponse,
    CreateAccountRequest,
    UpdateAccountRequest,
)
from snackbase.infrastructure.api.schemas.role_schemas import (
    CreateRoleRequest,
    RoleListItem,
    RoleListResponse,
    RoleResponse,
    UpdateRoleRequest,
)
from snackbase.infrastructure.api.schemas.migration_query_schemas import (
    CurrentRevisionResponse,
    MigrationHistoryItemResponse,
    MigrationHistoryResponse,
    MigrationListResponse,
    MigrationRevisionResponse,
)
from snackbase.infrastructure.api.schemas.file_schemas import (
    FileMetadataResponse,
    FileUploadResponse,
)
from snackbase.infrastructure.api.schemas.email_schemas import (
    EmailTemplateRenderRequest,
    EmailTemplateRenderResponse,
    EmailTemplateResponse,
    EmailTemplateTestRequest,
    EmailTemplateUpdate,
)

__all__ = [
    "AccountDetailResponse",
    "AccountListItem",
    "AccountListResponse",
    "AccountResponse",
    "AccountUserResponse",
    "AccountUsersResponse",
    "AuditLogResponse",
    "AuthResponse",
    "CollectionListItem",
    "CollectionListResponse",
    "CollectionResponse",
    "ConflictErrorResponse",
    "CreateAccountRequest",
    "CreateCollectionRequest",
    "CreateRoleRequest",
    "CurrentRevisionResponse",
    "DashboardStats",
    "EmailTemplateRenderRequest",
    "EmailTemplateRenderResponse",
    "EmailTemplateResponse",
    "EmailTemplateTestRequest",
    "EmailTemplateUpdate",
    "FieldDefinition",
    "FileMetadataResponse",
    "FileUploadResponse",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "GetCollectionsParams",
    "InvitationAcceptRequest",
    "InvitationCreateRequest",
    "InvitationListResponse",
    "InvitationPublicResponse",
    "InvitationResponse",
    "InvitationStatus",
    "LoginRequest",
    "MigrationHistoryItemResponse",
    "MigrationHistoryResponse",
    "MigrationListResponse",
    "MigrationRevisionResponse",
    "RecentRegistration",
    "RecordListResponse",
    "RecordResponse",
    "RecordValidationErrorDetail",
    "RecordValidationErrorResponse",
    "RefreshRequest",
    "RegisterRequest",
    "RegistrationResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "RoleListItem",
    "RoleListResponse",
    "RoleResponse",
    "SchemaFieldResponse",
    "SendVerificationRequest",
    "SystemHealthStats",
    "TokenRefreshResponse",
    "UpdateAccountRequest",
    "UpdateCollectionRequest",
    "UpdateRoleRequest",
    "UserResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
    "VerifyEmailRequest",
    "VerifyResetTokenResponse",
]
