"""API Schemas for request/response validation."""

from snackbase.infrastructure.api.schemas.auth_schemas import (
    AccountResponse,
    AuthResponse,
    ConflictErrorResponse,
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    TokenRefreshResponse,
    UserResponse,
    ValidationErrorDetail,
    ValidationErrorResponse,
)
from snackbase.infrastructure.api.schemas.collection_schemas import (
    CollectionListItem,
    CollectionListResponse,
    CollectionResponse,
    CreateCollectionRequest,
    FieldDefinition,
    GetCollectionsParams,
    SchemaFieldResponse,
    UpdateCollectionRequest,
)
from snackbase.infrastructure.api.schemas.invitation_schemas import (
    InvitationAcceptRequest,
    InvitationCreateRequest,
    InvitationListResponse,
    InvitationResponse,
    InvitationStatus,
)
from snackbase.infrastructure.api.schemas.permission_schemas import (
    CreatePermissionRequest,
    OperationRuleSchema,
    PermissionListResponse,
    PermissionResponse,
    PermissionRulesSchema,
)
from snackbase.infrastructure.api.schemas.record_schemas import (
    RecordListResponse,
    RecordResponse,
    RecordValidationErrorDetail,
    RecordValidationErrorResponse,
)
from snackbase.infrastructure.api.schemas.dashboard_schemas import (
    DashboardStats,
    RecentRegistration,
    SystemHealthStats,
)
from snackbase.infrastructure.api.schemas.audit_log_schemas import AuditLogResponse
from snackbase.infrastructure.api.schemas.account_schemas import (
    AccountDetailResponse,
    AccountListItem,
    AccountListResponse,
    AccountUserResponse,
    AccountUsersResponse,
    CreateAccountRequest,
    UpdateAccountRequest,
)
from snackbase.infrastructure.api.schemas.role_schemas import (
    CollectionPermission,
    CreateRoleRequest,
    RoleListItem,
    RoleListResponse,
    RolePermissionsResponse,
    RoleResponse,
    TestRuleRequest,
    TestRuleResponse,
    UpdateRolePermissionsRequest,
    UpdateRoleRequest,
    ValidateRuleRequest,
    ValidateRuleResponse,
)
from snackbase.infrastructure.api.schemas.bulk_permissions_schema import (
    BulkPermissionUpdate,
    BulkPermissionUpdateRequest,
    BulkPermissionUpdateResponse,
)
from snackbase.infrastructure.api.schemas.migration_query_schemas import (
    CurrentRevisionResponse,
    MigrationHistoryItemResponse,
    MigrationHistoryResponse,
    MigrationListResponse,
    MigrationRevisionResponse,
)
from snackbase.infrastructure.api.schemas.file_schemas import (
    FileMetadataResponse,
    FileUploadResponse,
)

__all__ = [
    "AccountDetailResponse",
    "AccountListItem",
    "AccountListResponse",
    "AccountResponse",
    "AccountUserResponse",
    "AccountUsersResponse",
    "AuditLogResponse",
    "AuthResponse",
    "BulkPermissionUpdate",
    "BulkPermissionUpdateRequest",
    "BulkPermissionUpdateResponse",
    "CollectionListItem",
    "CollectionListResponse",
    "CollectionPermission",
    "CollectionResponse",
    "ConflictErrorResponse",
    "CreateAccountRequest",
    "CreateCollectionRequest",
    "CreatePermissionRequest",
    "CreateRoleRequest",
    "CurrentRevisionResponse",
    "DashboardStats",
    "FieldDefinition",
    "FileMetadataResponse",
    "FileUploadResponse",
    "GetCollectionsParams",
    "InvitationAcceptRequest",
    "InvitationCreateRequest",
    "InvitationListResponse",
    "InvitationResponse",
    "InvitationStatus",
    "LoginRequest",
    "MigrationHistoryItemResponse",
    "MigrationHistoryResponse",
    "MigrationListResponse",
    "MigrationRevisionResponse",
    "OperationRuleSchema",
    "PermissionListResponse",
    "PermissionResponse",
    "PermissionRulesSchema",
    "RecentRegistration",
    "RecordListResponse",
    "RecordResponse",
    "RecordValidationErrorDetail",
    "RecordValidationErrorResponse",
    "RefreshRequest",
    "RegisterRequest",
    "RoleListItem",
    "RoleListResponse",
    "RolePermissionsResponse",
    "RoleResponse",
    "SchemaFieldResponse",
    "SystemHealthStats",
    "TestRuleRequest",
    "TestRuleResponse",
    "TokenRefreshResponse",
    "UpdateAccountRequest",
    "UpdateCollectionRequest",
    "UpdateRolePermissionsRequest",
    "UpdateRoleRequest",
    "UserResponse",
    "ValidateRuleRequest",
    "ValidateRuleResponse",
    "ValidationErrorDetail",
    "ValidationErrorResponse",
]
